name: Deploy .NET Core Web Application to IIS Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout of the Code
        uses: actions/checkout@v3
    
      - name: Install .NET Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.300'
    
      - name: Verify the .NET Installation
        run: dotnet --version
    
      - name: Build the Application with .NET
        run: dotnet build --configuration Release
    
      - name: Publish the Deployment Package in public folder
        run: dotnet publish -c Release -o public

      - name: Zip the public folder
        run: zip -r public.zip public/

    - name: Check weather Zip file is created or not
      run: ls -l public.zip